server:
  port: 8080
spring:
  application:
    name: JavaWebApp
  api:
    prefix: /api
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=JavaWebApp;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1234$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuanflute275@gmail.com
    password: myap bpep pura oyqj
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
      ssl:
        trust: smtp.gmail.com
    default-encoding: UTF-8

  # health check
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        base-path: /api/v1/actuator
        exposure:
          include: "health,info,metrics,error"
logging:
  level:
    org.springframework.security: DEBUG

